version: "3"
services:
  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_PASSWORD_MANAGER_API_BASE=http://${IP}:4000
        - REACT_APP_IMAGE_DECRYPTOR_API_BASE=http://${IP}:8000
        - REACT_APP_PI=${REACT_APP_PI}
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_PASSWORD_MANAGER_API_BASE=http://${IP}:4000
      - REACT_APP_IMAGE_DECRYPTOR_API_BASE=http://${IP}:8000
      - REACT_APP_PI=${REACT_APP_PI}

  password_manager:
    build:
      context: ./microservices/password-manager
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - HOST=0.0.0.0
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/primistore
      - PIPE_PATH=/command-runner
      - PIPE_COMM_DIR=/pipe-comm
      - HOST_PIPE_COMM_DIR=${PIPE_COMM_DIR}
      - LOCAL_DIR=/root/.primistore
    volumes:
      - ${LOCAL_DIR}:/root/.primistore
      - ${PIPE_PATH}:/command-runner
      - ${PIPE_COMM_DIR}:/pipe-comm

  image_decryptor:
    build:
      context: ./microservices/image-decryptor
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/primistore
    volumes:
      - ${LOCAL_DIR}:/root/.primistore

  mongodb:
    image: mongo:bionic
    ports:
      - "27017:27017"
