version: "3"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE=http://${IP}:4000

  password_manager:
    build:
      context: ./microservices/password-manager
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - HOST=0.0.0.0
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/primistore

  image_decryptor:
    build:
      context: ./microservices/image-decryptor
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:bionic
    ports:
      - "27017:27017"
